#!/bin/sh
#****************************************************************#
# ScriptName: build.sh
# Author: $yunlong.xyl@alibaba-inc.com
# Create Date: 2019-07-22 19:01
# Modify Author: $SHTERM_REAL_USER@alibaba-inc.com
# Modify Date: 2020-09-18 17:49
# Function: 
#***************************************************************#
