syntax = "proto3";

package tensorflow;
option cc_enable_arenas = true;
import "tensorflow/core/protobuf/config.proto";
import "tensorflow/core/protobuf/rewriter_config.proto";

message CallableOption {
  bool auto_adapt_device = 1;
  repeated string feed_on_device = 2;
  repeated string fetch_on_device = 3;
}

message WarmupValue {
  int32 start = 1;
  int32 end = 2;
}

message BlazeRunOptions {
  repeated int32 warmup_batchsize = 1;
  bool xla_compilation = 2;
  bool gemm_optimization = 3;
  bool auto_mixed_precision = 4;
  // CUDAGraphOptions cuda_graph = 5; deleted
  int32 virtual_gpus_per_device = 6;
  int32 inter_op_threads = 7;
  int32 intra_op_threads = 8;
  repeated string no_warmup_inputs = 9;

  // Callable option is disabled when use single threaded executor, because
  // single threaded executor force feed and fetch operations must be on device.
  bool use_single_threaded_executor = 10;
  // Make callable to specify the feed and fetch device
  bool callable_adapt_device = 11;
  //[DYNAMIC-SHAPE]
  bool gemm_dynamic_shape = 12;
  // The max batch size to use cpu predictor
  int32 max_batch_for_cpu = 13;
  int32 cpu_buckets_nums = 14;
  // Disable output padding
  bool disable_output_padding = 15;
  uint64 unit_flops = 16; //override measured values
  bool debug_batchsize = 100;
  int64 dump_timeline_interval = 101;
  ConfigProto config_proto = 102;
  map<string, WarmupValue> warmup_value = 103;
}
