load('//tensorflow:tensorflow.bzl', 'transitive_hdrs')

cc_library(
    name = 'traffic',
    srcs = ['traffic.cc',],
    hdrs = ['traffic.h',],
    linkopts = [
        '-lpthread',
    ],
    visibility = ["//visibility:public"],
)
